
spring:
  h2:
    console: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      fail_on_empty_beans: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: YOUR_GOOGLE_CLIENT_ID
            clientSecret: YOUR_GOOGLE_CLIENT_SECRET
            scope:
              - email
              - profile